module.exports = {
  log: function() {
    console.log(' DDDDDDDDDDDDDDD       EEEEEEEEEEEEEEEEEE  LLLLLL          TTTTTTTTTTTTTTTTTT    AAAAAAA        ')
    console.log(' DDDDDDDDDDDDDDDDD     EEEEEEEEEEEEEEEEEE  LLLLLL          TTTTTTTTTTTTTTTTTT    AAAAAAAA       ')
    console.log(' DDDDDDDDDDDDDDDDDD    EEEEEEEEEEEEEEEEEE  LLLLLL          TTTTTTTTTTTTTTTTTT   AAAAAAAAA       ')
    console.log(' DDDDDDDDDDDDDDDDDD    EEEEEEEEEEEEEEEEEE  LLLLLL          TTTTTTTTTTTTTTTTTT   AAAAAAAAA       ')
    console.log(' DDDDDD    DDDDDDDDD   EEEEEE              LLLLLL                TTTTTT        AAAAAAAAAAA      ')
    console.log(' DDDDDD      DDDDDDD   EEEEEE              LLLLLL                TTTTTT        AAAAAAAAAAA      ')
    console.log(' DDDDDD       DDDDDDD  EEEEEE              LLLLLL                TTTTTT        AAAAAAAAAAAA     ')
    console.log(' DDDDDD        DDDDDD  EEEEEE              LLLLLL                TTTTTT       AAAAAA AAAAAA     ')
    console.log(' DDDDDD        DDDDDD  EEEEEE              LLLLLL                TTTTTT       AAAAAA AAAAAA     ')
    console.log(' DDDDDD        DDDDDD  EEEEEEEEEEEEEEEEE   LLLLLL                TTTTTT       AAAAA   AAAAAA    ')
    console.log(' DDDDDD        DDDDDD  EEEEEEEEEEEEEEEEE   LLLLLL                TTTTTT      AAAAAA   AAAAAA    ')
    console.log(' DDDDDD        DDDDDD  EEEEEEEEEEEEEEEEE   LLLLLL                TTTTTT      AAAAAA   AAAAAA    ')
    console.log(' DDDDDD        DDDDDD  EEEEEEEEEEEEEEEEE   LLLLLL                TTTTTT     AAAAAA     AAAAAA   ')
    console.log(' DDDDDD        DDDDDD  EEEEEE              LLLLLL                TTTTTT     AAAAAAAAAAAAAAAAA   ')
    console.log(' DDDDDD        DDDDDD  EEEEEE              LLLLLL                TTTTTT     AAAAAAAAAAAAAAAAA   ')
    console.log(' DDDDDD       DDDDDDD  EEEEEE              LLLLLL                TTTTTT    AAAAAAAAAAAAAAAAAAA  ')
    console.log(' DDDDDD      DDDDDDD   EEEEEE              LLLLLL                TTTTTT    AAAAAAAAAAAAAAAAAAA  ')
    console.log(' DDDDDD    DDDDDDDDD   EEEEEE              LLLLLL                TTTTTT    AAAAAA       AAAAAAA ')
    console.log(' DDDDDDDDDDDDDDDDDD    EEEEEEEEEEEEEEEEEE  LLLLLLLLLLLLLLLLL     TTTTTT   AAAAAA         AAAAAA ')
    console.log(' DDDDDDDDDDDDDDDDDD    EEEEEEEEEEEEEEEEEE  LLLLLLLLLLLLLLLLL     TTTTTT   AAAAAA         AAAAAA ')
    console.log(' DDDDDDDDDDDDDDDDD     EEEEEEEEEEEEEEEEEE  LLLLLLLLLLLLLLLLL     TTTTTT  AAAAAAA         AAAAAA ')
    console.log(' DDDDDDDDDDDDDDD       EEEEEEEEEEEEEEEEEE  LLLLLLLLLLLLLLLLL     TTTTTT  AAAAAA           AAAAA ')
  }
}
